package wizard

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/imamik/k8zner/internal/config"
	"gopkg.in/yaml.v3"
)

// WriteConfig writes the config to a YAML file with a descriptive header.
func WriteConfig(cfg *config.Config, outputPath string) error {
	// Generate YAML content
	yamlBytes, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	// Build the complete file content with header
	var sb strings.Builder
	sb.WriteString(generateHeader())
	sb.WriteString("\n")
	sb.Write(yamlBytes)

	// Write to file
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0600); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

// generateHeader creates the YAML file header comment.
func generateHeader() string {
	return fmt.Sprintf(`# k8zner cluster configuration
# Generated by: k8zner init
# Generated at: %s
# Docs: https://github.com/imamik/k8zner
#
# Required environment variable:
#   HCLOUD_TOKEN - Your Hetzner Cloud API token
#
# Usage:
#   export HCLOUD_TOKEN=<your-token>
#   k8zner apply -c %s
`, time.Now().Format(time.RFC3339), "cluster.yaml")
}

// FileExists checks if a file exists at the given path.
func FileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// ConfirmOverwrite prompts the user to confirm overwriting an existing file.
func ConfirmOverwrite(path string) (bool, error) {
	fmt.Printf("\nFile already exists: %s\n", path)
	fmt.Print("Overwrite? (y/n): ")

	var response string
	if _, err := fmt.Scanln(&response); err != nil {
		return false, err
	}

	response = strings.ToLower(strings.TrimSpace(response))
	return response == "y" || response == "yes", nil
}
