version: 2

project_name: k8zner

builds:
  - main: ./cmd/k8zner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  github:
    owner: imamik
    name: k8zner
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

# Homebrew tap
brews:
  - name: k8zner
    repository:
      owner: imamik
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update {{ .ProjectName }} to {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/imamik/k8zner"
    description: "Production-ready Kubernetes clusters on Hetzner Cloud using Talos Linux"
    license: "Apache-2.0"
    install: |
      bin.install "k8zner"

      # Install shell completions
      generate_completions_from_executable(bin/"k8zner", "completion")
    test: |
      system "#{bin}/k8zner", "version"

# Announce release (optional - uncomment if desired)
# announce:
#   twitter:
#     enabled: false
#   discord:
#     enabled: false
