{{- if and .Values.credentials.hcloudToken (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8zner-operator.fullname" . }}-credentials
  labels:
    {{- include "k8zner-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.existingSecretKey }}: {{ .Values.credentials.hcloudToken | quote }}
{{- end }}
