# Example deployment for testing Cloudflare DNS and TLS integration
# This creates a simple whoami service with automatic DNS and TLS certificate provisioning.
#
# Prerequisites:
# 1. Cloudflare addon enabled with API token
# 2. External-DNS addon enabled
# 3. Cert-manager with Cloudflare DNS01 solver enabled
# 4. An ingress controller (traefik or nginx) enabled
#
# Usage:
# 1. Replace "whoami.example.com" with your actual domain
# 2. Apply with: kubectl apply -f whoami-test.yaml
# 3. Wait for DNS propagation and certificate issuance
# 4. Test with: curl https://whoami.example.com/
#
# To verify:
# - Check DNS: dig +short whoami.example.com
# - Check certificate: kubectl describe certificate whoami-tls -n default
# - Check external-dns logs: kubectl logs -n external-dns -l app.kubernetes.io/name=external-dns
# - Check cert-manager logs: kubectl logs -n cert-manager -l app.kubernetes.io/name=cert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: default
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default
  labels:
    app: whoami
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: default
  annotations:
    # External-DNS will read this annotation and create the DNS record
    external-dns.alpha.kubernetes.io/hostname: whoami.example.com
    # Tell cert-manager which ClusterIssuer to use
    # Use letsencrypt-cloudflare-staging for testing, then switch to -production
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-staging
    # Optional: force HTTPS redirect (for traefik)
    # traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  # Use the appropriate ingress class for your setup
  ingressClassName: traefik  # or "nginx" if using ingress-nginx
  tls:
  - hosts:
    - whoami.example.com
    secretName: whoami-tls  # cert-manager will create this secret
  rules:
  - host: whoami.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 80
